In [1]:
list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(list)

In [4]:
arr

array([1, 2, 3])

In [5]:
mat2d = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(mat2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5,3)

array([[0.85136455, 0.70964047, 0.58138089],
       [0.9575881 , 0.44444026, 0.74952428],
       [0.3185247 , 0.62526556, 0.79391166],
       [0.9473311 , 0.982005  , 0.81983967],
       [0.93694282, 0.15775318, 0.11116861]])

In [19]:
np.random.randn(2)

array([-0.14701893,  1.39105523])

In [22]:
arr = np.random.randint(0,50,10)

In [23]:
arr

array([25, 48, 23, 41, 34, 28, 35,  6, 45, 19])

In [24]:
arr.reshape(2,5)

array([[25, 48, 23, 41, 34],
       [28, 35,  6, 45, 19]])

In [25]:
arr.max()

48

In [26]:
arr.min()

6

In [27]:
arr.argmax()

1

In [29]:
arr.shape

(10,)

In [30]:
arr.dtype

dtype('int32')

In [34]:
from numpy.random import randint

In [36]:
randint(0,5,10)

array([3, 0, 1, 0, 1, 0, 4, 2, 4, 0])